### ISSUE TITLE
Bugs on Inventory module

### ISSUE THREAD

**Issue by ckming94** [KageyamaJie/Pfizer-Pharmacy#10]
Bugs 1:
The system able to return the stock quantity that are more than the quantity on hand. The current quantity of the stock in the database is lower than the required quantity that user want to be return, logically this should not be able to run. For example, current stock quantity for Product A is 10, user want to return 12, logically it should fail due to not enough stock to be return.

Bugs 2:
User able to enter alphabet in the quantity field and it will force the system to be freeze due to wrong input entered and the system are not able to perform anything since there are an error occurred.

**Comment by ManfredOoi** [comment]
Solution for first problem:
Check the stock quantity with the quantity that user want to be return, only return the stock if the stock quantity on hand is equal or more than user enter quantity.

Solution for second problem:
Using keyListener to prevent user on entering alphabet character into the quantity field.
