### ISSUE TITLE
Bug on Member module

### ISSUE THREAD

**Issue by WongKaiSung** [KageyamaJie/Pfizer-Pharmacy#12]
First problem:
The membership ID is manually entered by the user. If the user entering the ID where existing the database long time ago, it will cause data redundancy in the Membership data file.

Second problem:
There is unidentified problem that most of the user do not meet or without intend to trigger it. The problem only occurs when the user retrieve and prepare to update the particular detail at the same time, the user want to delete that particular record same as retrieved for update. If the user delete the record first, so that the user back to update membership there, the data will still leave on the text field and the user still able to press on the update button and prompt a successful update message.

**Comment by ckming94** [comment]
Solution for Bug 1:
To solve the current issue, the system should able to retrieve the latest ID in the Membership data file, once the latest member ID is retrieve out from database, the system will perform ID increment function, for example the latest ID is “M0002”, after the incremental process done, the new ID will be “M0003” set on the membership ID text field and disable the text field being rewrite by user. Therefore the data redundancy is resolved.

Solution for Bug 2:
To rectify the existing checking problem is to check again the data existence once the user click on update button to ensure the record will existing in the database.

**Comment by WongKaiSung** [comment]
okay, i will try to solve it.
