### ISSUE TITLE
Minor mistake on user story description

### ISSUE THREAD

**Issue by ckming94** [KageyamaJie/Pfizer-Pharmacy#6]
I found that are some minor mistake on constructing the user stories, such as, declare admin as a manager.

**Comment by KageyamaJie** [comment]
So how do we resolve for this issue?

**Comment by ManfredOoi** [comment]
The problem i have faced in the orderPage, the sales module, is the user can select member as customer type to get a 10% discount rate without checking the membership ID, second problem is the user can enter any random number act as credit card number, after that the customer still can purchase using credit card eventhrough the credit card is invalid

**Comment by ckming94** [comment]
I already make amendment for those mistake. Now all of it are good to go.
