### ISSUE TITLE
Bugs on Sales Module (orderPage.java)

### ISSUE THREAD

**Issue by ManfredOoi** [KageyamaJie/Pfizer-Pharmacy#7]
The problem i have faced in the Sales Module, the sales module, is the user can select member as customer type to get a 10% discount rate without checking the membership ID, second problem is the user can enter any random number act as credit card number, after that the customer still can purchase using credit card even though the credit card is invalid.

**Comment by ckming94** [comment]
My suggestion is add in a textbox (or pop out message dialog) for capturing the membership ID and then the system can make verification on user input so that only the existing member able to enjoy 10% discount rate.

**Comment by ManfredOoi** [comment]
The problem solved already, now i uploading the file feel free to check
