### ISSUE TITLE
Bug on Login  module (login.java)

### ISSUE THREAD

**Issue by WongKaiSung** [KageyamaJie/Pfizer-Pharmacy#8]
I found that there are two problem in the login module, the first problem is whenever user enter a correct password with a wrong user name the user still able to login to the system.
Second problem is when user enter wrong user name and wrong password the system do not give any message. So the user does not know whether the system is hanging or the user have entered wrong user name or password.

**Comment by ckming94** [comment]
For the first problem I suggest while doing validation, you should also include checking the username as well, after the username is true, only the the password whether the user entered password match with the password that in the same record of the username.
The second problem, you may need to use message dialog to show a pop out message to tell the user what's wrong with the current situation.

**Comment by WongKaiSung** [comment]
Okay, I get it.
